---
- name: Kernel tuning
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  with_items: "{{ genv.kernel }}"

- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
